#![no_main]
#![allow(dead_code)]

use libfuzzer_sys::fuzz_target;

mod protocol {
    include!("../../src/protocol.rs");
}

fuzz_target!(|data: &[u8]| {
    if data.len() > u16::MAX as usize {
        return;
    }

    let payload = data.to_vec();
    let padded = protocol::apply_padding(&payload);
    let recovered = protocol::remove_padding(&padded).expect("padding generated by apply_padding is valid");
    assert_eq!(recovered, payload.as_slice());
});
